name: slacker
description: Post a message to a Slack channel

inputs:
  webhook:
    description: The Slack webhook to post to
    required: true
  status:
    description: The status of the GitHub Action.
    required: true
runs:
  using: docker
  image: Dockerfile
