name: cicd
on:
  push:
    branches:
      - main
      - master

jobs:
  cicd:
    name: CI/CD %ACTION%
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test latest version of %ACTION%
        uses: ./
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}
