name: cicd
on:
  push:
    branches:
      - main
      - master

jobs:
  cicd:
    name: CI/CD for %ACTION%
    runs-on: ubuntu-20.04
    if: |
      !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test latest version of %ACTION%
        uses: ./
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}

      - name: Notify Slack
        if: always()
        uses: jmpa-oss/job-to-slack@v0.0.1
        with:
            webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
            status: ${{ job.status }}
