name: test
on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Test job-notify
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test latest version
        uses: ./
        with:
          webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
          status: ${{ job.status }}
