on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Test action
        uses: jmpa-oss/slacker-action@v0.0.2
        with:
          token: ${{ github.actor }}

